model:
  faster_rcnn:
    num_classes: 37

train_input_reader:
  tf_record_input_reader:
    input_path:
      - data/pet_faces_train.record-?????-of-00010
  label_map_path: object_detection/data/pet_label_map.pbtxt

eval_input_reader:
  tf_record_input_reader:
    input_path:
      - data/pet_faces_val.record-?????-of-00010
  label_map_path: object_detection/data/pet_label_map.pbtxt
  shuffle: no
  num_readers: 1
